import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { LoadingProvider } from "@/components/LoadingContext";
import Providers from "@/providers/query-provider";
import NextTopLoader from "nextjs-toploader";

// FONTS GLOBAL
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "SmartPresence",
  description: "Generated by SmartPresence",
  icons: {
    icon: "/logo1.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextTopLoader
            color="oklch(39.356% 0.10171 263.904)"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
          />
        <Providers>
          <LoadingProvider>
            <main>{children}</main>
            <Toaster
              position="top-right"
              richColors
              toastOptions={{
                duration: 5000,
                style: {
                  borderRadius: "8px",
                  fontWeight: "500",
                },
              }}
            />
          </LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
